# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - Azure-Django-Web

on:
  push:
    branches:
      - Blog
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          ls
          pip install -r requirements.txt
          cd firstproject
          python ./manage.py collectstatic --noinput
      
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EE616ACDDE4C493584FE0C1E029CCA33 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BB0A6F597B1F43B296F49CAC88F23A45 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D78E19EE5AC742E18D36B53BDE6C8FFF }}

      - name: Set environment variables on Azure Web App
        run: |
            az webapp config appsettings set --name 'Azure-Django-Web' --resource-group 'deploy' --settings \
              DB_NAME=${{ secrets.DB_NAME }} \
              DB_USER=${{ secrets.DB_USER }} \
              DB_PASS=${{ secrets.DB_PASS }} \
              DB_HOST=${{ secrets.DB_HOST }} \
              SECRET_KEY='${{ secrets.SECRET_KEY }}' \
              PORT=8000 \
              WEBSITE_PORT=8000 \
              WEBSITES_PORT=8000 \
              WEBSITE_RUN_FROM_PACKAGE=1 


      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'Azure-Django-Web'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}