# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - Azure-Django-Web-test

on:
  push:
    branches:
      - Blog
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
            python -m pip install --upgrade pip
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      
      - name: Collect static files
        run: |
              source venv/bin/activate
              cd firstproject
              python manage.py collectstatic --noinput
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      # - name: Set environment variables on Azure Web App
      #   run: |
      #       az webapp config appsettings set --name 'Azure-Django-Web-test' --resource-group 'Azure-Django-Web-test_group' --settings \
      #         DB_NAME=${{ secrets.AZURE_MYSQL_NAME }} \
      #         DB_USER=${{ secrets.AZURE_MYSQL_USER }} \
      #         DB_PASS=${{ secrets.AZURE_MYSQL_PASSWORD }} \
      #         DB_HOST=${{ secrets.AZURE_MYSQL_HOST }} \
      #         SECRET_KEY='${{ secrets.SECRET_KEY }}' \
      #         PORT=8000 \
      #         WEBSITES_PORT=8000 \
      #         ENABLE_ORYX_BUILD=true \
      #         WEBSITE_RUN_FROM_PACKAGE=1 
        

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'Azure-Django-Web-test'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4691507D80C44AAF9E11348263E61EFF }}
          # 選basic就好自動幫你產生publish-profile，免費版的話就不用設定publish-profile