# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - Azure-Django-Web

on:
  push:
    branches:
      - Blog
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Create Procfile
        run: |
            echo "web: venv/bin/gunicorn --bind 0.0.0.0:8000 --timeout 600 firstproject.wsgi:application" > Procfile

      - name: Collect static files
        run: |
          source venv/bin/activate
          cd firstproject
          python manage.py collectstatic --noinput

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "venv/*" "release.zip"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: 'https://azure-django-web.azurewebsites.net'
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E92FF502FD2F4E9580C1F664FA41F3D6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CBD94531A7504A8BBDF61959546303C8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_696086DF1A5D40A6BB8587671314F5FE }}

      - name: Set environment variables on Azure Web App
        run: |
            az webapp config appsettings set --name 'Azure-Django-Web' --resource-group 'deploy' --settings \
              DB_NAME=${{ secrets.DB_NAME }} \
              DB_USER=${{ secrets.DB_USER }} \
              DB_PASS=${{ secrets.DB_PASS }} \
              DB_HOST=${{ secrets.DB_HOST }} \
              SECRET_KEY='${{ secrets.SECRET_KEY }}' \
              PORT=8000 \
              WEBSITES_PORT=8000 \
              ENABLE_ORYX_BUILD=true \
              WEBSITE_RUN_FROM_PACKAGE=1 

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'Azure-Django-Web'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: Activate virtual environment and start application
        run: |
            source venv/bin/activate
            gunicorn --bind 0.0.0.0:8000 --timeout 600 firstproject.wsgi:application