name: Build and deploy Python app to Azure Web App - Azure-Django-Web

on:
  push:
    branches:
      - Blog
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.12'

      - name: Set up virtual environment
        run: |
          cd firstproject
          python -m venv venv
          source venv/bin/activate  
#          myenv\Scripts\activate     # 在 Windows 上
        

      - name: Install dependencies
        run: |
          cd firstproject
          pip install --upgrade pip
          pip install -r firstproject/requirements.txt 

      - name: Check Django project
        run: |
          cd firstproject
          python manage.py check

      - name: Collect static files
        run: |
          cd firstproject
          python manage.py collectstatic --noinput
        # working-directory: firstproject

      - name: Set PYTHONPATH
        run: export PYTHONPATH=$(pwd)

      - name: Zip artifact for deployment
        run: |
          cd firstproject
          zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            firstproject/release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          # creds 是 Azure 登入的密碼，需在 Github 的 Secrets 設定
          # 怎麼設定 Secrets 請參考 https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E92FF502FD2F4E9580C1F664FA41F3D6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CBD94531A7504A8BBDF61959546303C8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_696086DF1A5D40A6BB8587671314F5FE }}
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set environment variables on Azure Web App
        run: |
          az webapp config appsettings set --name 'Azure-Django-Web' --resource-group 'deploy' --settings \
          DB_NAME=${{ secrets.DB_NAME }} \
          DB_USER=${{ secrets.DB_USER }} \
          DB_PASS=${{ secrets.DB_PASS }} \
          DB_HOST=${{ secrets.DB_HOST }} \
          SECRET_KEY=${{ secrets.SECRET_KEY }} \
          WEBSITE_RUN_FROM_PACKAGE=1


      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Azure-Django-Web'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
